DEBUG: true
SIMULATION:
    GRID_SIZE: 3
    POPULATION: 1000
    N_PUBLISHERS: 10
    N_PLATFORMS: 10
    CONTACT_RATE: 0.1
    GRAVITY_STRETCH: 100
    MAX_INFLUENCE: 0.1
    ATTENTION_BUDGET: 100
    CONTENT_SAMPLE_SIZE: 50
    BASE_SIGNUP_RATE: 0.001
    DATA_PER_CONSUME: 0.0001
    REVENUE_PER_AD: 0.001
    MAX_PLATFORMS: 3
    UNFOLLOW_TRUST: 0.1
    FOLLOW_TRUST: 0.9
    UNSUBSCRIBE_TRUST: 0.1
    SUBSCRIBE_TRUST: 0.9
    UNSUBSCRIBE_LAG: 20
    BASE_CONVERSION_RATE: 0.01
    MAX_CONVERSION_RATE: 0.05
    MAX_SHARED_CONTENT: 200
    COST_PER_QUALITY: 0.2
    PUBLISHER:
        REVENUE_PER_SUBSCRIBER: 1000
        BASE_BUDGET: 50000
