DEBUG: true
SIMULATION:
    POPULATION: 1000
    N_PUBLISHERS: 10
    N_PLATFORMS: 10
    CONTACT_RATE: 0.1
    GRAVITY_STRETCH: 100
    MAX_INFLUENCE: 0.1
    SUBSCRIPTION_PROB_WEIGHT: 0.1
    CONTENT_SAMPLE_SIZE: 50
    BASE_SIGNUP_RATE: 0.001
    DATA_PER_CONSUME: 0.0001
    REVENUE_PER_AD: 0.001
    MAX_PLATFORMS: 3
    PUBLISHER:
        REVENUE_PER_SUBSCRIBER: 0.01
        BASE_BUDGET: 10
