DEBUG: true
SIMULATION:
    GRID_SIZE: 5
    POPULATION: 10000
    N_PUBLISHERS: 10
    N_PLATFORMS: 0
    CONTACT_RATE: 0.2
    GRAVITY_STRETCH: 100
    MAX_INFLUENCE: 0.1
    CONTENT_SAMPLE_SIZE: 50
    BASE_SIGNUP_RATE: 0.001
    DATA_PER_CONSUME: 0.000001
    REVENUE_PER_AD: 0.05
    MAX_PLATFORMS: 3
    DEFAULT_TRUST: 0.4
    UNFOLLOW_TRUST: 0.1
    FOLLOW_TRUST: 0.9
    UNSUBSCRIBE_TRUST: 0.2
    SUBSCRIBE_TRUST: 0.7
    UNSUBSCRIBE_LAG: 20
    BASE_CONVERSION_RATE: 0.01
    MAX_CONVERSION_RATE: 0.05
    MAX_SHARED_CONTENT: 200
    COST_PER_QUALITY: 0.5
    ECONOMY: 1.
    PUBLISHER:
        REVENUE_PER_SUBSCRIBER: 0.01
        BASE_BUDGET: 2000
    AGENT:
        ATTENTION_BUDGET: 20
    PUBLISHERS:
        - BASE_BUDGET: 5000
          MOTIVE: Profit
